# Generated by Django 5.0.6 on 2024-06-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.FloatField(verbose_name='Cart Total')),
            ],
            options={
                'verbose_name': 'ShoppingCart',
                'verbose_name_plural': 'ShoppingCarts',
                'db_table': 'shopping_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaystactPaymentProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
            ],
            options={
                'db_table': 'payment_processor_Paystack',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ShoppingCartService',
                'verbose_name_plural': 'ShoppingCartServices',
                'db_table': 'shopping_cart_service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StripePaymentProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
            ],
            options={
                'db_table': 'payment_processor_Stripe',
                'managed': True,
            },
        ),
    ]
