# Generated by Django 5.0.6 on 2024-06-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaystactPaymentProcessor',
            new_name='PaystackPaymentProcessor',
        ),
    ]
